### ISSUE TITLE
More flexible strings for community stats

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-translations#17]
*I've discussed this briefly with Dessalines in PMs already. He told me to open an issue, so here I am.*

At the moment, it's impossible to correctly translate the community stats bubbles and their tooltips (the "x users active in the last day/week/month" ones).

In English, these strings don't have any variations depending on the count of users and days/weeks/months nor in the gender of said time windows. For example, "3 users active in the last week" would be "3 utilizadores ativos na última semana" in Portuguese, however, this is just what can be achieved now:

![imagem](https://user-images.githubusercontent.com/35771816/133124250-bf158796-a1b9-41ca-ad2f-3af026a045fa.png)

This is, as far as I know, an existing problem in other romance languages as well.

More strings need to be added to provide the needed flexibility i18n needs.

**Comment by dessalines** [comment]
This shouldn't be too difficult to add. Its just some `{{count}} active users per month`, `{{count}} active users per day`... etc.

**Comment by dessalines** [comment]
This is done now.
