### ISSUE TITLE
settings do not change to  korean language

### ISSUE THREAD

**Issue by 7942app** [LemmyNet/lemmy-translations#7]
The lemmy.ml site setting menu does not change to Korean.
I don't know exactly why, but when I select a Korean language a few months ago, the English menu comes up.
If I change to another country's language, it will change to that country's language.
Tested on various browsers such as Chrome, Firefox and Edge.
(I'm sorry I'm not familiar with English.)

Questions not related to the content:
Can I delete a specific country language?

**Comment by dessalines** [comment]
It looks like a ton of korean translations just got added two hours ago, so they won't get added until the next release.

Unfortunately you cannot delete a language, your users can choose any language they like that we have available.
