### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by Generator** [LemmyNet/lemmy-translations#71]
Already tried to 3 ou 4 times to create new account on https://weblate.join-lemmy.org/ goes to "verification mail" page but never received any mail.   
Tried with gmail and protonmail

**Comment by salif** [comment]
Me too. I didn't receive email

**Comment by ismailkarsli** [comment]
Same. Can we directly create PR here for it? @dessalines

**Comment by orl0pl** [comment]
Me too

**Comment by orl0pl** [comment]
I think that is fixed now. I received the email.

**Comment by Generator** [comment]
Now when trying to register returns with "405 Not Allowed"
