### ISSUE TITLE
confusing German localization error

### ISSUE THREAD

**Issue by tjumar** [LemmyNet/lemmy-translations#78]
Hello,
under user settings -> languages there is a pretty confusing localization error:

In English: "Warning: If you deselect Undetermined, you will not see most content."
In German: "Warnung: Wenn du "unbestimmt" wählst, wirst du die meisten Inhalte nicht sehen."
It has the opposite meaning of the English warning: If you choose "undetermined,", you will not see most of the content.
It should be something like "Wenn du "unbestimmt" nicht wählst, wirst du die meisten Inhalte nicht sehen."
Or "abwählst" instead of "nicht wählst".
Additionally, if set to German, there is no "unbestimmt" in the listing of languages only Undetermined.

I noticed the error on lemmy.world which has these versions at the moment: 
UI: 0.18.1-rc.7
BE: 0.18.1-rc.4

**Comment by jorgesumle** [comment]
[Fixed now](https://weblate.join-lemmy.org/translate/lemmy/lemmy/de/?checksum=aba87ba375db862f)!

*Ich bin kein Muttersprachler, aber ich würde "deaktivieren" anstatt "nicht wählen" sagen. Wenn das nicht stimmt, kannst du das in Weblate ändern*.

> Additionally, if set to German, there is no "unbestimmt" in the listing of languages only Undetermined.

https://github.com/LemmyNet/lemmy-ui/issues/1166

**Comment by tjumar** [comment]
Thanks for the quick fix!
