### ISSUE TITLE
The word "ago" can't be translated

### ISSUE THREAD

**Issue by UncleReaton** [LemmyNet/lemmy-translations#8]
On a user profile there is the line "joined **x**M ago". The problem is that for every language you can only translate the word "joined" so the word "ago" stays in english.  
[Here is the example with the Spanish and the French version.](https://imgur.com/a/nHI3Iuf)

**Comment by dessalines** [comment]
I'm not getting this issue, which tells me its a browser locale problem. What browser are you using?

![image](https://user-images.githubusercontent.com/930215/108930256-97e8ba80-7613-11eb-9e6d-c028e2a44d52.png)

Secondly, there's only one reference to "ago" in the code, and its for english locales only. All the time locale work is handled by moment: `{moment.utc(this.props.data.updated).fromNow(!this.props.showAgo)}`

**Comment by UncleReaton** [comment]
Oh yes, my bad. I just had to refresh, I don't know why I didn't try that, I feel so dumb. Thanks for the answer though.

**Comment by dessalines** [comment]
No probs.
