### ISSUE TITLE
Add the Ukrainian translation to upcoming release 

### ISSUE THREAD

**Issue by Digharatta** [LemmyNet/lemmy-translations#92]
Greetings!

The Ukrainian Weblate translation of Lemmy is ready. Please include it in the upcoming release.

**Comment by dessalines** [comment]
It'll get added in the next release.

**Comment by Digharatta** [comment]
Thank you! 🙏

**Comment by Digharatta** [comment]
Hello,
It seems that the Ukrainian language has not been added to the 0.18.5 release. 
Please add it to the upcoming release.
Thank you in advance 🙏

**Comment by dessalines** [comment]
Will do :)

**Comment by Digharatta** [comment]
Congratulations on your new release! Another step towards freeing people from corporate monopolies.
Ukrainians also suffer from these monopolies on Facebook and Twitter and will appreciate Lemmy in Ukrainian.
